import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const BlackSansaProFont = localFont({
  src: "./assets/fonts/projekt-blackbird-v2.otf",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={BlackSansaProFont.className}>{children}</body>
    </html>
  );
}
